py_binary(
    name = "company_logo",
    srcs = ["company_logo.py"],
    main = "company_logo.py",
)

py_test(
    name = "company_logo_test",
    srcs = ["company_logo_test.py"],
    deps = [":company_logo"]
)