py_binary(
    name = "nested_lists",
    srcs = ["nested_lists.py",],
    main = "nested_lists.py"
)

py_test(
    name = "nested_lists_test",
    srcs = ["nested_lists_test.py"],
    deps = [":nested_lists"]
)

py_binary(
    name = "lists",
    srcs = ["lists.py",],
    main = "lists.py"
)
