py_binary(
    name = "nested_lists",
    srcs = ["nested_lists.py",],
    main = "nested_lists.py"
)

py_test(
    name = "nested_lists_test",
    srcs = ["nested_lists_test.py"],
    deps = [":nested_lists"]
)

py_binary(
    name = "lists",
    srcs = ["lists.py",],
    main = "lists.py"
)

py_binary(
    name = "list_comps",
    srcs = ["list_comps.py",],
    main = "list_comps.py"
)

py_test(
    name = "list_comps_test",
    srcs = ["list_comps_test.py"],
    deps = [":list_comps"]
)

py_binary(
    name = "tuples_hashing",
    srcs = ["tuples_hashing.py",],
    main = "tuples_hashing.py"
)

py_test(
    name = "tuples_hashing_test",
    srcs = ["tuples_hashing_test.py"],
    deps = [":tuples_hashing"]
)
