py_binary(
    name = "map_character",
    srcs = ["map_character.py"],
    main = "map_character.py"
)

py_test(
    name = "map_character_test",
    srcs = ["map_character_test.py"],
    deps = [":map_character"]
)