py_binary(
    name = "sum_of_list_of_nums",
    srcs = ["sum_of_list_of_nums.py"],
    main = "sum_of_list_of_nums.py",
)

py_binary(
    name = "deci_num_conversion",
    srcs = ["deci_num_conversion.py"],
    main = "deci_num_conversion.py",
)

py_binary(
    name = "deci_num_conv_stack",
    srcs = ["deci_num_conv_stack.py"],
    deps = ["//data_structures/probl_sol_with_algs_and_ds/ch03_basic_ds:stack_lib",],
    main = "deci_num_conv_stack.py",
)

py_binary(
    name = "palindrome",
    srcs = ["palindrome.py"],
    main = "palindrome.py",
)

py_binary(
    name = "draw_spiral",
    srcs = ["draw_spiral.py"],
    main = "draw_spiral.py",
)

py_binary(
    name = "fractal_tree",
    srcs = ["fractal_tree.py"],
    main = "fractal_tree.py",
)

py_binary(
    name = "sierpinski_triangle",
    srcs = ["sierpinski_triangle.py"],
    main = "sierpinski_triangle.py",
)
