py_binary(
    name = "ch01_exercises",
    srcs = ["ch01_exercises.py"],
    main = "ch01_exercises.py",
)

py_test(
    name = "ch01_exercises_test",
    srcs = ["ch01_exercises_test.py",],
    deps = [":ch01_exercises",],
)

py_test(
    name = "ch01_exercises_gtest_test",
    srcs = ["ch01_exercises_gtest_test.py",],
    deps = [":ch01_exercises",],
)
