py_binary(
    name = "ch01_exercises",
    srcs = ["ch01_exercises.py"],
    main = "ch01_exercises.py",
)

py_test(
    name = "ch01_exercises_test",
    srcs = ["ch01_exercises_test.py",],
    deps = [":ch01_exercises",],
)

# Not working
# py_test(
#    name = "ch01_exercises_gtest_test",
#    srcs = ["ch01_exercises_gtest_test.py",],
#    deps = [":ch01_exercises",],
# )

py_binary(
    name = "ch02_oops",
    srcs = ["ch02_oops.py",],
    main = "ch02_oops.py",
)

py_test(
    name = "ch02_oops_test",
    srcs = ["ch02_oops_test.py",],
    deps = [":ch02_oops",],
)

py_binary(
    name = "ch02_op_overlo_vector",
    srcs = ["ch02_op_overlo_vector.py",],
    main = "ch02_op_overlo_vector.py",
)
