py_binary(
    name = "sequential_search",
    srcs = ["sequential_search.py"],
    main = "sequential_search.py",
)

py_binary(
    name = "ordered_seq_search",
    srcs = ["ordered_seq_search.py"],
    main = "ordered_seq_search.py",
)

py_binary(
    name = "binary_search",
    srcs = ["binary_search.py"],
    main = "binary_search.py",
)

py_binary(
    name = "binary_search_recursive",
    srcs = ["binary_search_recursive.py"],
    main = "binary_search_recursive.py",
)

# Sorting Algorithms
py_binary(
    name = "bubble_sort",
    srcs = ["bubble_sort.py"],
    main = "bubble_sort.py",
)

py_binary(
    name = "selection_sort",
    srcs = ["selection_sort.py"],
    main = "selection_sort.py",
)

py_binary(
    name = "insertion_sort",
    srcs = ["insertion_sort.py"],
    main = "insertion_sort.py",
)

py_binary(
    name = "merge_sort",
    srcs = ["merge_sort.py"],
    main = "merge_sort.py",
)

py_binary(
    name = "quick_sort",
    srcs = ["quick_sort.py"],
    main = "quick_sort.py",
)
