py_binary(
    name = "swap_case",
    srcs = ["swap_case.py"],
    main = "swap_case.py"
)

py_test(
    name = "swap_case_test",
    srcs = ["swap_case_test.py"],
    deps = [":swap_case"]
)

py_binary(
    name = "split_and_join",
    srcs = ["split_and_join.py"],
    main = "split_and_join.py"
)

py_test(
    name = "split_and_join_test",
    srcs = ["split_and_join_test.py"],
    deps = [":split_and_join"]
)